window.Pomodoro = window.Pomodoro || {};

Pomodoro.dom = {
    minutes: document.getElementById('minutes'),
    seconds: document.getElementById('seconds'),
    sessionLabel: document.getElementById('session-label'),
    sessionCount: document.getElementById('session-count'),
    startBtn: document.getElementById('start-btn'),
    pauseBtn: document.getElementById('pause-btn'),
    resetBtn: document.getElementById('reset-btn'),
    themeToggle: document.getElementById('theme-toggle'),
    themeToggleIcon: document.querySelector('.theme-toggle-icon'),
    themeIcon: document.querySelector('.theme-toggle-icon'),
    settingsBtn: document.getElementById('settings-btn'),
    settingsModal: document.getElementById('settings-modal'),
    closeModal: document.getElementById('close-modal'),
    saveSettings: document.getElementById('save-settings'),
    workDuration: document.getElementById('work-duration'),
    shortBreakDuration: document.getElementById('short-break-duration'),
    longBreakDuration: document.getElementById('long-break-duration'),
    autoCycle: document.getElementById('auto-cycle'),
    soundEnabled: document.getElementById('sound-enabled'),
    dailyGoalTarget: document.getElementById('daily-goal-target'),
    tabBtns: document.querySelectorAll('.tab-btn'),
    timerDisplay: document.querySelector('.timer-display'),
    // Gamification elements
    characterAvatar: document.getElementById('character-avatar'),
    characterName: document.getElementById('character-name'),
    levelNum: document.getElementById('level-num'),
    xpText: document.getElementById('xp-text'),
    xpBar: document.getElementById('xp-bar'),
    streakCount: document.getElementById('streak-count'),
    dailyProgress: document.getElementById('daily-progress'),
    totalSessions: document.getElementById('total-sessions'),
    totalXp: document.getElementById('total-xp'),
    dailyGoalText: document.getElementById('daily-goal-text'),
    dailyGoalBar: document.getElementById('daily-goal-bar'),
    badgesGrid: document.getElementById('badges-grid'),
    badgesToggleBtn: document.getElementById('badges-toggle-btn'),
    badgesPanel: document.getElementById('badges-panel'),
    // Analytics elements
    analyticsToggleBtn: document.getElementById('analytics-toggle-btn'),
    analyticsPanel: document.getElementById('analytics-panel'),
    dailyChart: document.getElementById('daily-chart'),
    weeklyChart: document.getElementById('weekly-chart'),
    heatmapGrid: document.getElementById('heatmap-grid'),
    sessionHistoryList: document.getElementById('session-history-list'),
    bestDayValue: document.getElementById('best-day-value'),
    bestDayDate: document.getElementById('best-day-date'),
    totalFocusTime: document.getElementById('total-focus-time'),
    // Focus Environment elements
    focusToggleBtn: document.getElementById('focus-toggle-btn'),
    focusPanel: document.getElementById('focus-panel'),
    themeGrid: document.getElementById('theme-grid'),
    ambientControls: document.getElementById('ambient-controls'),
    ambientVolumeSlider: document.getElementById('ambient-volume'),
    spotifyEmbed: document.getElementById('spotify-embed'),
    spotifyIframe: document.getElementById('spotify-iframe'),
    spotifyUrlInput: document.getElementById('spotify-url-input'),
    spotifyLoadBtn: document.getElementById('spotify-load-btn'),
    spotifyResetBtn: document.getElementById('spotify-reset-btn'),
    soundcloudEmbed: document.getElementById('soundcloud-embed'),
    soundcloudIframe: document.getElementById('soundcloud-iframe'),
    soundcloudUrlInput: document.getElementById('soundcloud-url-input'),
    soundcloudLoadBtn: document.getElementById('soundcloud-load-btn'),
    soundcloudResetBtn: document.getElementById('soundcloud-reset-btn'),
    // Shield elements
    shieldEnabled: document.getElementById('shield-enabled'),
    shieldStrictMode: document.getElementById('shield-strict-mode'),
    shieldPenalty: document.getElementById('shield-penalty'),
    shieldThreshold: document.getElementById('shield-threshold'),
    // Tasks elements
    tasksToggleBtn: document.getElementById('tasks-toggle-btn'),
    tasksPanel: document.getElementById('tasks-panel'),
    taskInput: document.getElementById('task-input'),
    taskAddBtn: document.getElementById('task-add-btn'),
    taskList: document.getElementById('task-list'),
    tasksCount: document.getElementById('tasks-count'),
    folderTabs: document.getElementById('folder-tabs')
};
